### ISSUE TITLE
bug in submit_cityscapes_WideResNet38_decouple.sh

### ISSUE THREAD

**Issue by daixiaolei623** [lxtGH/DecoupleSegNets#28]
@lxtGH 
thank you for your sharing
but when i run the sh ./scripts/submit_test/submit_cityscapes_WideResNet38_decouple.sh , i got the error:

'eval test:   0%|                                       | 0/1525 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/pdb.py", line 1699, in main
    pdb._runscript(mainpyfile)
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/pdb.py", line 1568, in _runscript
    self.run(statement)
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/bdb.py", line 578, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/dai/code/semantic_segmentation/24/DecoupleSegNets-master/eval.py", line 5, in <module>
    """
  File "/home/dai/code/semantic_segmentation/24/DecoupleSegNets-master/eval.py", line 616, in main
    for iteration, data in enumerate(pbar):
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/tqdm/std.py", line 1178, in __iter__
    for obj in iterable:
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
    data = self._next_data()
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1085, in _next_data
    return self._process_data(data)
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
    data.reraise()
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/dai/code/semantic_segmentation/24/DecoupleSegNets-master/datasets/cityscapes.py", line 263, in __getitem__
    img = Image.open(img_path).convert('RGB')
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/PIL/Image.py", line 904, in convert
    self.load()
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/PIL/ImageFile.py", line 274, in load
    raise_oserror(err_code)
  File "/home/dai/anaconda3/envs/DecoupleSegNets/lib/python3.7/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: codec configuration error when reading image file

Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program'

Could you please tell me how to solve it?
thank you.

**Comment by lxtGH** [comment]
Please pull the new update code
