### ISSUE TITLE
./pretrained_models/wider_resnet38.pth.tar

### ISSUE THREAD

**Issue by Youzhihui** [lxtGH/DecoupleSegNets#29]
Traceback (most recent call last):
  File "C:/Users/yzh/Desktop/DecoupleSegNets-master/train.py", line 416, in <module>
    main()
  File "C:/Users/yzh/Desktop/DecoupleSegNets-master/train.py", line 182, in main
    net = network.get_net(args, criterion)
  File "C:\Users\yzh\Desktop\DecoupleSegNets-master\network\__init__.py", line 16, in get_net
    criterion=criterion)
  File "C:\Users\yzh\Desktop\DecoupleSegNets-master\network\__init__.py", line 44, in get_model
    net = net_func(num_classes=num_classes, criterion=criterion)
  File "C:\Users\yzh\Desktop\DecoupleSegNets-master\network\deepv3.py", line 249, in __init__
    raise RuntimeError("=====================Could not load ImageNet weights of WideResNet38 network.=======================")
RuntimeError: =====================Could not load ImageNet weights of WideResNet38 network.=======================
Please download the ImageNet weights of WideResNet38 in our repo to ./pretrained_models/wider_resnet38.pth.tar.

I can not find your ImageNet weights of WideResNet38 in your repo, where it is?
could you tell me?

**Comment by lxtGH** [comment]
Hi just comment out this line. We just use the Mapillary pretrained model for WideResNet38.

**Comment by Youzhihui** [comment]
ok, thank you very much
