### ISSUE TITLE
Trainging error about  'train_cityscapes_W38_decouple.sh'

### ISSUE THREAD

**Issue by Joker1994k** [lxtGH/DecoupleSegNets#5]
Hi, thank you for sharing your great work! 

When training with the script 'train_cityscapes_W38_decouple.sh',  I met

~~~
Traceback (most recent call last):                                                                                                                                                            
  File "train.py", line 416, in <module>                                                                                                                                                      
    main()                                                                                                                                                                                    
  File "train.py", line 183, in main                                                                                                                                                          
    optim, scheduler = optimizer.get_optimizer(args, net)                                                                                                                                     
  File "/segmentation/DecoupleSegNets/optimizer.py", line 37, in get_optimizer                                                                                                     
    raise ValueError('ERROR Cannot Do Scale Poly')                                                                                                                                            
ValueError: ERROR Cannot Do Scale Poly
~~~

When I read the code, I find the reason is parameter REDUCE_BORDER_EPOCH is set to -1 and lr_schedule is set to 'scl-polyoccur' at the same time. Can you give some advice about how to set these parameters? Thx

**Comment by lxtGH** [comment]
I will update the file in one week

**Comment by lxtGH** [comment]
The config has been updated~
